### ISSUE TITLE
`scrt init` arguments mismatch with documentation

### ISSUE THREAD

**Issue by chilladx** [loderunner/scrt#16]
Hi,

The [README](https://github.com/loderunner/scrt/blob/main/README.md) presents the `init` sub-command as:

```
scrt init --storage=local \
          --password=p4ssw0rd \
          --local-path=~/.scrt/store.scrt
```

But this sub-command does not work as is:

```
$ scrt init --storage=local --password=p4ssw0rd --local-path=~/.scrt/store.scrt
Error: missing store location
Usage:
  scrt init [flags]

Flags:
  -h, --help        help for init
      --overwrite   overwrite store if it exists

Global Flags:
  -c, --config string     configuration file
      --location string   store location
  -p, --password string   master password to unlock the store
      --storage string    storage type
```

Note that `init` is expecting a `--location` parameter with the path:

```
$ scrt init --storage=local --password=p4ssw0rd --location=~/.scrt/store.scrt
local store initialized at ~/.scrt/store.scrt
```

You'll find the same code in [this example](https://github.com/loderunner/scrt/blob/main/README.md#initialization), [this example](https://github.com/loderunner/scrt/blob/main/README.md#example-1) and [this one](https://github.com/loderunner/scrt/blob/main/README.md#local) have the same problem.

**Comment by loderunner** [comment]
Hey,

Thanks for pointing that out!

The `README.md` at [`v0.2.0`](https://github.com/loderunner/scrt/tree/v0.2.0) did mention the `--location` flag, but the repository advanced further than the release.

[`v0.3.2`](https://github.com/loderunner/scrt/releases/tag/v0.3.2) was just released and should fix that inconsistency.

We'll make a better effort in the future to keep the `main` branch in sync with the current release!

----

If you update to the latest version, remember to change your usage of `scrt`! Sorry for the inconsistencies and breaking changes. `scrt` is still in its alpha phase and we're moving fast to find out the best interface and usage patterns.
